# Generated by Django 5.1.7 on 2025-03-17 17:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "country",
                    models.CharField(
                        help_text="Название страны",
                        max_length=50,
                        verbose_name="country",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Название города", max_length=50, verbose_name="city"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Название улица", max_length=50, verbose_name="street"
                    ),
                ),
                ("house_number", models.IntegerField(help_text="Номер дома")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("model", models.CharField(max_length=200)),
                ("release_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_name",
                    models.CharField(
                        help_text="Название звена", max_length=120, verbose_name="name"
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "creation_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "element",
                    models.CharField(
                        choices=[
                            ("завод", "Завод"),
                            (
                                "индивидуальный предприниматель",
                                "Индивидуальный Предприниматель",
                            ),
                            ("розничная сеть", "Розничная Сеть"),
                        ]
                    ),
                ),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="network.contact",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_link",
                        to="network.network",
                    ),
                ),
                ("products", models.ManyToManyField(to="network.product")),
            ],
        ),
    ]
